version: "3.5"

networks:
  default:
    name: example.com

services:
  master:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/master.supervisord.conf
    container_name: master
    hostname: master
    domainname: example.com
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
      - 88:88/udp    # Kerberos
      - 749:749      # Kerberos
    tmpfs:
      - /tmp:noexec

  worker0:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/worker.supervisord.conf
    container_name: worker0
    hostname: worker0
    domainname: example.com
    ports:
      - 50010:50010  # DN
      - 50071:50075  # DN webui
      - 8040:8042    # NM webui
    tmpfs:
      - /tmp:noexec

  worker1:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/worker.supervisord.conf
    container_name: worker1
    hostname: worker1
    domainname: example.com
    ports:
      - 50011:50010  # DN
      - 50072:50075  # DN webui
      - 8041:8042    # NM webui
    tmpfs:
      - /tmp:noexec

  edge:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    environment:
      - HADOOP_TESTING_FIXUID=${HADOOP_TESTING_FIXUID:-1000}
      - HADOOP_TESTING_FIXGID=${HADOOP_TESTING_FIXGID:-1000}
    command: supervisord -c /etc/edge.supervisord.conf
    container_name: edge
    hostname: edge
    domainname: example.com
